"""Render the Threat Atlas into a browsable MCP Threat Encyclopedia (HTML).

This is the *human face* of the knowledge base: the same `threats.yaml` that
drives the scanner, presented as an OWASP-style, research-cited reference. It is
generated by ``mcp-audit intel build-docs``. Its visual language comes from
`_theme` — the same cream paper and offset shadows as the dashboard and the
playground, rather than the private sixteen-colour palette this page used to
carry. Pure string templating — no external dependencies, fully offline, never
executes anything.

The four lifecycle phases are the book's chapters, so they get the tier banner
and a number: a reader who lands here from a finding needs to know *when* in a
server's life the threat bites before they read a word about it.
"""

from __future__ import annotations

import html
from typing import Any

from ._theme import ATMOSPHERE_HTML, page_head

_PHASE_ORDER = ["creation", "deployment", "operation", "maintenance"]
_PHASE_LABEL = {
    "creation": "Creation",
    "deployment": "Deployment",
    "operation": "Operation",
    "maintenance": "Maintenance",
}
# All-caps, technical-poetic: what actually happens to a server in this phase.
_PHASE_TAGLINE = {
    "creation": "Where the tool is written and the lie is planted",
    "deployment": "Where the server meets a client that already trusts it",
    "operation": "Where the agent acts on whatever it was told",
    "maintenance": "Where an update rewrites what you already approved",
}
_DETECT_LABEL = {"yes": "Static", "partial": "Partial", "no": "Runtime / out of scope"}

# Page-specific layout. The palette, the type scale and the seven components
# arrive from `page_head`.
_CSS = """
.masthead { padding: 56px 0 8px; }
.masthead h1 { margin-bottom: 8px; }
.lede { max-width: 760px; margin-top: 14px; }
.stats { display: flex; gap: 10px; flex-wrap: wrap; margin-top: 20px; }
.stats span {
  font-family: var(--headline); font-size: 12px; letter-spacing: 3px; text-transform: uppercase;
  border: 2px solid var(--ink); background: var(--paper); color: var(--ink); padding: 4px 12px;
}

.threat { padding: 26px 22px 20px; }
.threat > header { display: flex; align-items: center; gap: 10px; flex-wrap: wrap; margin-bottom: 4px; }
.threat h3 { flex: 1 1 auto; }
.deck > .threat.sev-critical { box-shadow: 6px 6px 0 var(--red); }
.deck > .threat.sev-high { box-shadow: 6px 6px 0 var(--tangerine); }
.deck > .threat:hover { transform: translate(-2px, -2px); box-shadow: 8px 8px 0 var(--ink); }

.badge {
  font-family: var(--headline); font-size: 11px; letter-spacing: 2px; text-transform: uppercase;
  border: 2px solid var(--ink-soft); background: var(--cream); color: var(--ink-soft); padding: 1px 8px;
}
/* A threat the scanner cannot see is the other thing a reader must not miss, so
   it earns an outline of its own — the word inside says which kind of gap it is. */
.detect-no .badge.detect { border-color: var(--tangerine); color: var(--tangerine); background: var(--paper); }
.aliases { font-size: 12px; color: var(--ink-soft); margin-top: 4px; }
.summary { color: var(--ink); margin: 12px 0; }
.meta { display: grid; gap: 4px; font-size: 13px; margin-bottom: 10px; }
/* Named `rulechip`, not `rule`: `hr.rule` is a base-system class and a bare
   `.rule` here would reach into it. */
.rulechip {
  font-family: var(--mono); font-size: 12px; background: var(--cream-deep);
  border: 2px solid var(--ink); padding: 0 6px; margin-right: 4px; color: var(--ink);
}
.gap { color: var(--tangerine); font-weight: 700; }

details { border-top: 3px dashed var(--mondo); margin-top: 14px; padding-top: 12px; }
details > summary {
  cursor: pointer; font-family: var(--display); font-size: 12px; letter-spacing: 2px;
  color: var(--ink); text-transform: uppercase; list-style: none;
}
details > summary::marker { display: none; }
details > summary::-webkit-details-marker { display: none; }
details > summary::before { content: '\\25B8'; color: var(--orange); padding-right: 7px; }
details[open] > summary::before { content: '\\25BE'; }
.lesson { margin-top: 16px; }
.lesson-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin-top: 16px; }
.lesson h4, .lesson-grid h4 { margin-bottom: 4px; }
.lesson p, .lesson-grid p, .lesson li { font-size: 13px; }
.lesson ol, .lesson-grid ul { margin: 4px 0; padding-left: 18px; }
.lesson-grid li { font-size: 13px; margin: 2px 0; }
.cols { display: grid; grid-template-columns: 1fr 1fr; gap: 14px; margin-top: 16px; }
.cols ul { margin: 0; padding-left: 18px; }
.cols li { font-size: 13px; margin: 2px 0; }
.examples { display: grid; gap: 8px; }
.sources {
  margin-top: 16px; padding-top: 10px; border-top: 2px solid var(--cream-deep);
  font-size: 12px; color: var(--ink-soft); word-break: break-word;
}
.refs { margin-top: 40px; }
.refs li { margin: 6px 0; }

@media (max-width: 760px) { .cols, .lesson-grid { grid-template-columns: 1fr; } }
"""


def _esc(text: Any) -> str:
    return html.escape(str(text if text is not None else ""))


def _source_html(src: dict[str, Any]) -> str:
    if src.get("arxiv"):
        sec = f" §{_esc(src['section'])}" if src.get("section") else ""
        return (
            f'<a href="https://arxiv.org/abs/{_esc(src["arxiv"])}" target="_blank" rel="noopener">'
            f'{_esc(src.get("title") or "arXiv:" + str(src["arxiv"]))}</a>{sec}'
        )
    if src.get("type") == "cve" or src.get("id"):
        cid = src.get("id", "")
        name = f" ({_esc(src['name'])})" if src.get("name") else ""
        return (
            f'<a href="https://nvd.nist.gov/vuln/detail/{_esc(cid)}" target="_blank" rel="noopener">'
            f"{_esc(cid)}</a>{name}"
        )
    if src.get("section"):
        return f"§{_esc(src['section'])}"
    return _esc(src.get("title") or "source")


def _threat_card(threat: dict[str, Any], references: dict[str, dict]) -> str:
    sev = _esc(threat.get("severity", "info"))
    detect = threat.get("static_detectability", "no")
    rules = threat.get("rules", []) or []
    rules_html = (
        " ".join(f'<code class="rulechip">{_esc(r)}</code>' for r in rules)
        if rules
        else '<span class="gap">no rule yet — known gap</span>'
    )
    signals = "".join(f"<li>{_esc(s)}</li>" for s in threat.get("static_signals", []))
    mitigations = "".join(f"<li>{_esc(m)}</li>" for m in threat.get("mitigations", []))
    can_establish = "".join(
        f"<li>{_esc(item)}</li>" for item in threat.get("engine_can_establish", [])
    )
    cannot_establish = "".join(
        f"<li>{_esc(item)}</li>" for item in threat.get("engine_cannot_establish", [])
    )
    review_questions = "".join(
        f"<li>{_esc(item)}</li>" for item in threat.get("review_questions", [])
    )
    applies = ", ".join(str(item).replace("_", " ") for item in threat.get("applies_to", []))
    applicability = f"<span><b>Applies to:</b> {_esc(applies)}</span>" if applies else ""
    scenario = (
        f'<div class="lesson"><h4>Scenario</h4><p>{_esc(threat.get("scenario"))}</p></div>'
        if threat.get("scenario") else ""
    )
    evidence_boundary = ""
    if can_establish or cannot_establish:
        evidence_boundary = f"""
        <div class="lesson-grid">
          <div><h4>What the engine can establish</h4><ul>{can_establish or '<li>—</li>'}</ul></div>
          <div><h4>What it cannot establish</h4><ul>{cannot_establish or '<li>—</li>'}</ul></div>
        </div>"""
    reviewer = (
        f'<div class="lesson"><h4>Reviewer questions</h4><ol>{review_questions}</ol></div>'
        if review_questions else ""
    )
    examples = ""
    if threat.get("safe_example") or threat.get("risky_example"):
        examples = f"""
        <div class="examples">
          <div class="prompt good" data-tag="Safer pattern">{_esc(threat.get('safe_example', '—'))}</div>
          <div class="prompt bad" data-tag="Risky pattern">{_esc(threat.get('risky_example', '—'))}</div>
        </div>"""

    sources_rendered = []
    for src in threat.get("sources", []):
        s = dict(src)
        if s.get("ref") and s["ref"] in references:
            base = {k: v for k, v in references[s["ref"]].items() if k != "key"}
            base.update({k: v for k, v in s.items() if k != "ref"})
            s = base
        sources_rendered.append(_source_html(s))
    sources_html = " · ".join(sources_rendered)

    aliases = threat.get("aliases", [])
    aliases_html = (
        f'<div class="aliases">aka {_esc(", ".join(aliases))}</div>' if aliases else ""
    )

    return f"""
    <article class="block labelled threat sev-{sev} detect-{_esc(detect)}"
             data-label="{_esc(threat.get("id"))}">
      <header>
        <h3>{_esc(threat.get("name"))}</h3>
        <span class="chip {sev}">{sev}</span>
        <span class="badge detect">{_esc(_DETECT_LABEL.get(detect, detect))}</span>
      </header>
      {aliases_html}
      <p class="summary">{_esc(threat.get("summary"))}</p>
      <div class="meta">
        <span><b>Attacker:</b> {_esc(threat.get("attacker", "").replace("_", " "))}</span>
        <span><b>Lifecycle:</b> {_esc(threat.get("lifecycle", "").replace("_", " "))}</span>
        <span><b>Detected by:</b> {rules_html}</span>
        {applicability}
      </div>
      <details>
        <summary>Learn, verify &amp; mitigate</summary>
        {scenario}
        {evidence_boundary}
        {reviewer}
        {examples}
        <div class="cols">
          <div><h4>Static signals</h4><ul>{signals or "<li>—</li>"}</ul></div>
          <div><h4>Mitigations</h4><ul>{mitigations or "<li>—</li>"}</ul></div>
        </div>
      </details>
      <footer class="sources">Sources: {sources_html or "—"}</footer>
    </article>"""


def _phase_banner(phase: str, index: int, count: int) -> str:
    """The chapter break for one lifecycle phase.

    Numbered by position in the lifecycle rather than by how many phases
    happened to be non-empty, so `Operation` is always 03 no matter which Atlas
    version you are reading.
    """
    # tier / tier-2 / tier-3 cycle the accent across the chapter breaks.
    variant = ["", " tier-2", " tier-3"][index % 3]
    return f"""
<section class="tier{variant}">
  <div class="num">{index + 1:02d}</div>
  <div class="body">
    <span class="label">// Phase {index + 1:02d}</span>
    <h2>{_PHASE_LABEL[phase]} phase</h2>
    <p class="tagline">{_PHASE_TAGLINE[phase]}</p>
  </div>
  <div class="stripe">{count} threat{"s" if count != 1 else ""}</div>
</section>"""


def build_encyclopedia(atlas: dict[str, Any]) -> str:
    """Return a self-contained HTML string for the whole Atlas."""
    threats = atlas.get("threats", [])
    references = {r["key"]: r for r in atlas.get("references", []) if isinstance(r, dict) and "key" in r}
    version = _esc(atlas.get("version"))
    released = _esc(atlas.get("released"))

    by_phase: dict[str, list[dict]] = {p: [] for p in _PHASE_ORDER}
    for t in threats:
        by_phase.setdefault(t.get("phase_group", "operation"), []).append(t)

    n_static = sum(1 for t in threats if t.get("static_detectability") == "yes")
    n_partial = sum(1 for t in threats if t.get("static_detectability") == "partial")
    n_gap = sum(1 for t in threats if not t.get("rules"))

    sections = []
    for index, phase in enumerate(_PHASE_ORDER):
        items = by_phase.get(phase, [])
        if not items:
            continue
        cards = "".join(_threat_card(t, references) for t in items)
        sections.append(
            f'<section class="phase phase-{phase}">'
            f"{_phase_banner(phase, index, len(items))}"
            f'<div class="deck">{cards}</div></section>'
        )

    ref_lines = []
    for r in references.values():
        if r.get("arxiv"):
            ref_lines.append(
                f'<li><a href="https://arxiv.org/abs/{_esc(r["arxiv"])}" target="_blank" '
                f'rel="noopener">{_esc(r.get("title"))}</a> (arXiv:{_esc(r["arxiv"])})</li>'
            )

    return f"""<!DOCTYPE html>
<html lang="en">
{page_head(f"MCP Threat Encyclopedia · v{version}", _CSS)}
<body>
{ATMOSPHERE_HTML}
<div class="wrap">
<header class="masthead">
  <h1>MCP Threat<br>Encyclopedia</h1>
  <p class="subtitle">Definitions v{version} · released {released}</p>
  <p class="lede">The research-cited catalog behind <code>mcp-audit</code>. Every threat
  maps to a detection rule or an honest gap.</p>
  <div class="stats">
    <span>{len(threats)} threats</span>
    <span>{n_static} statically detectable</span>
    <span>{n_partial} partial</span>
    <span>{n_gap} known gaps</span>
  </div>
</header>
{''.join(sections)}
<hr class="rule">
<section class="block labelled refs" data-label="Sources">
  <h3>Primary sources</h3>
  <ul class="glyph">{''.join(ref_lines)}</ul>
</section>
<footer class="stamped">
  <div>
    <h2>Catalog complete</h2>
    <p class="meta">Generated from <code>threats.yaml</code> by
    <code>mcp-audit intel build-docs</code>.</p>
  </div>
  <div class="stamp">Definitions v{version}</div>
</footer>
</div>
</body>
</html>"""
