"""Render the Threat Atlas into a browsable MCP Threat Encyclopedia (HTML).

This is the *human face* of the knowledge base: the same `threats.yaml` that
drives the scanner, presented as an OWASP-style, research-cited reference. It is
generated by ``mcp-audit intel build-docs`` and shares its visual language with
the project's visual plan. Pure string templating — no external dependencies,
fully offline, never executes anything.
"""

from __future__ import annotations

import html
from typing import Any

_PHASE_ORDER = ["creation", "deployment", "operation", "maintenance"]
_PHASE_LABEL = {
    "creation": "Creation",
    "deployment": "Deployment",
    "operation": "Operation",
    "maintenance": "Maintenance",
}
_DETECT_LABEL = {"yes": "Static", "partial": "Partial", "no": "Runtime / out of scope"}


def _esc(text: Any) -> str:
    return html.escape(str(text if text is not None else ""))


def _source_html(src: dict[str, Any]) -> str:
    if src.get("arxiv"):
        sec = f" §{_esc(src['section'])}" if src.get("section") else ""
        return (
            f'<a href="https://arxiv.org/abs/{_esc(src["arxiv"])}" target="_blank" rel="noopener">'
            f'{_esc(src.get("title") or "arXiv:" + str(src["arxiv"]))}</a>{sec}'
        )
    if src.get("type") == "cve" or src.get("id"):
        cid = src.get("id", "")
        name = f" ({_esc(src['name'])})" if src.get("name") else ""
        return (
            f'<a href="https://nvd.nist.gov/vuln/detail/{_esc(cid)}" target="_blank" rel="noopener">'
            f"{_esc(cid)}</a>{name}"
        )
    if src.get("section"):
        return f"§{_esc(src['section'])}"
    return _esc(src.get("title") or "source")


def _threat_card(threat: dict[str, Any], references: dict[str, dict]) -> str:
    sev = _esc(threat.get("severity", "info"))
    detect = threat.get("static_detectability", "no")
    rules = threat.get("rules", []) or []
    rules_html = (
        " ".join(f'<code class="rule">{_esc(r)}</code>' for r in rules)
        if rules
        else '<span class="gap">no rule yet — known gap</span>'
    )
    signals = "".join(f"<li>{_esc(s)}</li>" for s in threat.get("static_signals", []))
    mitigations = "".join(f"<li>{_esc(m)}</li>" for m in threat.get("mitigations", []))

    sources_rendered = []
    for src in threat.get("sources", []):
        s = dict(src)
        if s.get("ref") and s["ref"] in references:
            base = {k: v for k, v in references[s["ref"]].items() if k != "key"}
            base.update({k: v for k, v in s.items() if k != "ref"})
            s = base
        sources_rendered.append(_source_html(s))
    sources_html = " · ".join(sources_rendered)

    aliases = threat.get("aliases", [])
    aliases_html = (
        f'<div class="aliases">aka {_esc(", ".join(aliases))}</div>' if aliases else ""
    )

    return f"""
    <article class="card sev-{sev} detect-{_esc(detect)}">
      <header>
        <span class="tid">{_esc(threat.get("id"))}</span>
        <h3>{_esc(threat.get("name"))}</h3>
        <span class="badge sev">{sev}</span>
        <span class="badge detect">{_esc(_DETECT_LABEL.get(detect, detect))}</span>
      </header>
      {aliases_html}
      <p class="summary">{_esc(threat.get("summary"))}</p>
      <div class="meta">
        <span><b>Attacker:</b> {_esc(threat.get("attacker", "").replace("_", " "))}</span>
        <span><b>Lifecycle:</b> {_esc(threat.get("lifecycle", "").replace("_", " "))}</span>
        <span><b>Detected by:</b> {rules_html}</span>
      </div>
      <details>
        <summary>Static signals &amp; mitigations</summary>
        <div class="cols">
          <div><h4>Static signals</h4><ul>{signals or "<li>—</li>"}</ul></div>
          <div><h4>Mitigations</h4><ul>{mitigations or "<li>—</li>"}</ul></div>
        </div>
      </details>
      <footer class="sources">Sources: {sources_html or "—"}</footer>
    </article>"""


def build_encyclopedia(atlas: dict[str, Any]) -> str:
    """Return a self-contained HTML string for the whole Atlas."""
    threats = atlas.get("threats", [])
    references = {r["key"]: r for r in atlas.get("references", []) if isinstance(r, dict) and "key" in r}
    version = _esc(atlas.get("version"))
    released = _esc(atlas.get("released"))

    by_phase: dict[str, list[dict]] = {p: [] for p in _PHASE_ORDER}
    for t in threats:
        by_phase.setdefault(t.get("phase_group", "operation"), []).append(t)

    n_static = sum(1 for t in threats if t.get("static_detectability") == "yes")
    n_partial = sum(1 for t in threats if t.get("static_detectability") == "partial")
    n_gap = sum(1 for t in threats if not t.get("rules"))

    sections = []
    for phase in _PHASE_ORDER:
        items = by_phase.get(phase, [])
        if not items:
            continue
        cards = "".join(_threat_card(t, references) for t in items)
        sections.append(
            f'<section class="phase phase-{phase}"><h2>{_PHASE_LABEL[phase]} phase</h2>'
            f'<div class="grid">{cards}</div></section>'
        )

    ref_lines = []
    for r in references.values():
        if r.get("arxiv"):
            ref_lines.append(
                f'<li><a href="https://arxiv.org/abs/{_esc(r["arxiv"])}" target="_blank" '
                f'rel="noopener">{_esc(r.get("title"))}</a> (arXiv:{_esc(r["arxiv"])})</li>'
            )

    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>MCP Threat Encyclopedia · v{version}</title>
<style>{_CSS}</style></head>
<body>
<header class="top">
  <h1>MCP Threat Encyclopedia</h1>
  <p class="lede">The research-cited catalog behind <code>mcp-audit</code>. Every threat
  maps to a detection rule or an honest gap. Definitions version <b>{version}</b>
  · released {released}.</p>
  <div class="stats">
    <span>{len(threats)} threats</span>
    <span>{n_static} statically detectable</span>
    <span>{n_partial} partial</span>
    <span>{n_gap} known gaps</span>
  </div>
</header>
{''.join(sections)}
<section class="refs"><h2>Primary sources</h2><ul>{''.join(ref_lines)}</ul></section>
<footer class="foot">Generated from <code>threats.yaml</code> by <code>mcp-audit intel build-docs</code>.</footer>
</body></html>"""


_CSS = """
:root{--bg:#0e1116;--card:#171c24;--ink:#e6edf3;--mut:#9aa7b4;--line:#262d38;
--crit:#ff5d5d;--high:#ff9f43;--med:#ffd166;--low:#5fb3ff;--info:#7d8997;--ok:#3fb950;}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);
font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
.top{padding:40px 24px 24px;max-width:1100px;margin:0 auto}
h1{margin:0 0 6px;font-size:30px}.lede{color:var(--mut);max-width:720px}
.stats{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}
.stats span{background:var(--card);border:1px solid var(--line);border-radius:999px;
padding:4px 12px;font-size:13px;color:var(--mut)}
.phase{max-width:1100px;margin:0 auto;padding:14px 24px}
.phase h2{font-size:18px;border-left:3px solid var(--low);padding-left:10px;color:var(--ink)}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(330px,1fr));gap:14px}
.card{background:var(--card);border:1px solid var(--line);border-radius:12px;padding:16px;
border-left:4px solid var(--info)}
.card.sev-critical{border-left-color:var(--crit)}.card.sev-high{border-left-color:var(--high)}
.card.sev-medium{border-left-color:var(--med)}.card.sev-low{border-left-color:var(--low)}
.card header{display:flex;align-items:center;gap:8px;flex-wrap:wrap}
.card h3{margin:0;font-size:16px;flex:1 1 auto}
.tid{font:600 11px ui-monospace,monospace;color:var(--mut);background:#0c1218;
border:1px solid var(--line);border-radius:6px;padding:2px 6px}
.badge{font-size:11px;border-radius:6px;padding:2px 8px;text-transform:capitalize}
.badge.sev{background:#2a1414;color:var(--high)}.sev-critical .badge.sev{color:var(--crit)}
.badge.detect{background:#0c1a12;color:var(--ok)}.detect-no .badge.detect{color:var(--info)}
.detect-partial .badge.detect{color:var(--med)}
.aliases{color:var(--mut);font-size:12px;margin:6px 0 0}
.summary{color:#cbd5e1;margin:10px 0}
.meta{font-size:13px;color:var(--mut);display:flex;flex-direction:column;gap:3px;margin-bottom:8px}
.rule{background:#102016;color:var(--ok);border-radius:5px;padding:1px 6px;font-size:12px;margin-right:3px}
.gap{color:var(--info);font-style:italic}
details summary{cursor:pointer;color:var(--low);font-size:13px}
.cols{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:8px}
.cols h4{margin:6px 0 4px;font-size:12px;color:var(--mut);text-transform:uppercase;letter-spacing:.04em}
.cols ul{margin:0;padding-left:16px}.cols li{font-size:13px;color:#cbd5e1;margin:2px 0}
.sources{margin-top:10px;padding-top:8px;border-top:1px solid var(--line);font-size:12px;color:var(--mut)}
.sources a{color:var(--low)}
.refs{max-width:1100px;margin:0 auto;padding:24px}.refs a{color:var(--low)}
.foot{max-width:1100px;margin:0 auto;padding:24px;color:var(--mut);font-size:13px}
@media(max-width:560px){.cols{grid-template-columns:1fr}}
"""
